---
include:
  - board: nice_nano_v2
    shield: corne-v4_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: corne-v4_right nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: settings_reset
  # - board: corne_v4_left
  #   snippet: studio-rpc-usb-uart
  # - board: corne-v4_right

