---
include:
  - board: charybdis_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
  - board: charybdis_right
    shield: nice_view
  # - board: corne-v4_left
  #   snippet: studio-rpc-usb-uart
  # - board: corne-v4_right

