---
include:
  - board: corne_v4_left
    shield: nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: corne_v4_right
    shield: nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: settings_reset
  # - board: corne_v4_left
  #   snippet: studio-rpc-usb-uart
  # - board: corne-v4_right

